# Generated by Django 4.0.3 on 2022-04-16 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsmsApp', '0002_petrol_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0, max_length=(15, 2))),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('petrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsmsApp.petrol')),
            ],
            options={
                'verbose_name_plural': 'Stock-In Records',
            },
        ),
    ]
