# Generated by Django 4.0.3 on 2022-04-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmsApp', '0005_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=0, max_length=(15, 2)),
        ),
    ]
